# Generated by Django 5.1.5 on 2025-05-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_is_published_alter_post_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img_url",
            field=models.CharField(max_length=500),
        ),
    ]
